services:
  db:
    restart: always
    image: postgres:latest
    environment:
      POSTGRES_DB: mastodon
      POSTGRES_USER: mastodon
      POSTGRES_PASSWORD: mastodon
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_mastodon:/var/lib/postgresql/data
    networks:
      - mastodon_network
      - reverse_proxy
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'mastodon']

  redis:
    restart: always
    image: redis:latest
    networks:
      - mastodon_network
      - reverse_proxy
    volumes:
      - /home/redis:/data
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']

  web:
    build: .
    image: tomkahe/mastodon:v4.3.0-rc.1
    restart: always
    user: root
    command: bash -c "rm -f /mastodon/tmp/pids/server.pid; bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - .env.production
    networks:
      - mastodon_network
      - reverse_proxy
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    volumes:
      - /home/tomakahe:/config
      - /srv/dev-disk-by-uuid-540ab9c8-fa76-426e-91a8-7afeddcd5d2d/mastodon-data:/mastodon/public/system
   # extra_hosts:
     # - "xn--6r9aa.com:192.168.1.75"
    #  - "ꩮꩮ.com:192.168.1.75"

  streaming:    # You can uncomment the following lines if you want to not use the prebuilt image, for example if you have local code changes
    build:
      dockerfile: ./streaming/Dockerfile
      context: .
    image: tomkahe/mastodon-streaming:v4.3.0-rc.1

    restart: always
    command: node ./streaming
    user: root
    healthcheck:
      test: ['CMD-SHELL', "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1"]
    env_file:
      - .env.production
    networks:
      - mastodon_network
      - reverse_proxy
    ports:
      - "4000:4000"
    depends_on:
      - db
      - redis
    volumes:
      - /home/tomakahe:/config
   # extra_hosts:
   #   - "xn--6r9aa.com:192.168.1.75"
   #   - "ꩮꩮ.com:192.168.1.75"

  sidekiq:
    build: .
    image: tomkahe/mastodon:v4.3.0-rc.1
    user: root
    restart: always
    command: bundle exec sidekiq -c 100
    env_file:
      - .env.production
    depends_on:
      - db
      - redis
    networks:
      - mastodon_network
      - reverse_proxy
    volumes:
      - /home/tomakahe:/config
      - /srv/dev-disk-by-uuid-540ab9c8-fa76-426e-91a8-7afeddcd5d2d/mastodon-data:/mastodon/public/system
   # extra_hosts:
   #   - "xn--6r9aa.com:192.168.1.16"
   #   - "ꩮꩮ.com:192.168.1.75"

networks:
  mastodon_network:
    driver: bridge
  reverse_proxy:
    driver: bridge

volumes:
  postgres_mastodon:
