# This file is designed for production server deployment, not local development work
# For a containerized local dev environment, see: https://github.com/mastodon/mastodon/blob/main/docs/DEVELOPMENT.md#docker

services:
  db:
    restart: always
    image: postgres:16-alpine
    shm_size: 256mb
    environment:
      POSTGRES_DB: mastodon
      POSTGRES_USER: mastodon
      POSTGRES_PASSWORD: mastodon
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
      POSTGRES_HOST_AUTH_METHOD: 'trust'
    networks:
      - mastodon_network
      - reverse_proxy
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'mastodon']
    volumes:
      - postgres_mastodon:/var/lib/postgresql/data

  redis:
    restart: always
    image: redis:7-alpine
    networks:
      - mastodon_network
      - reverse_proxy
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
    volumes:
      - ./home/redis:/data

  # es:
  #   restart: always
  #   image: docker.elastic.co/elasticsearch/elasticsearch:7.17.4
  #   environment:
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m -Des.enforce.bootstrap.checks=true"
  #     - "xpack.license.self_generated.type=basic"
  #     - "xpack.security.enabled=false"
  #     - "xpack.watcher.enabled=false"
  #     - "xpack.graph.enabled=false"
  #     - "xpack.ml.enabled=false"
  #     - "bootstrap.memory_lock=true"
  #     - "cluster.name=es-mastodon"
  #     - "discovery.type=single-node"
  #     - "thread_pool.write.queue_size=1000"
  #   networks:
  #      - external_network
  #      - internal_network
  #   healthcheck:
  #      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
  #   volumes:
  #      - ./elasticsearch:/usr/share/elasticsearch/data
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #     nofile:
  #       soft: 65536
  #       hard: 65536
  #   ports:
  #     - '127.0.0.1:9200:9200'

  web:
    build: .
    image: tomkahe/mastodon:v4.3.6
    user: root
    restart: always
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    networks:
      - mastodon_network
      - reverse_proxy
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL',"curl -s --noproxy localhost localhost:3000/health | grep -q 'OK' || exit 1"]
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
      # - es
    volumes:
      - /home/tomakahe:/config
      - /srv/dev-disk-by-uuid-540ab9c8-fa76-426e-91a8-7afeddcd5d2d/mastodon-data:/mastodon/public/system
   # extra_hosts:
     # - "xn--6r9aa.com:192.168.1.75"
    #  - "ꩮꩮ.com:192.168.1.75"

  streaming:    # You can uncomment the following lines if you want to not use the prebuilt image, for example if you have local code changes
    build:
      dockerfile: ./streaming/Dockerfile
      context: .
    image: tomkahe/mastodon-streaming:v4.3.6
    restart: always
    env_file: .env.production
    command: node ./streaming/index.js
    networks:
      - mastodon_network
      - reverse_proxy
    healthcheck:
      # prettier-ignore
      test: ['CMD-SHELL', "curl -s --noproxy localhost localhost:4000/api/v1/streaming/health | grep -q 'OK' || exit 1"]
    ports:
      - '4000:4000'
    depends_on:
      - db
      - redis

  sidekiq:
    build: .
    image: tomkahe/mastodon:v4.3.6
    user: root
    restart: always
    env_file: .env.production
    command: bundle exec sidekiq -c 15
    depends_on:
      - db
      - redis
    networks:
      - mastodon_network
      - reverse_proxy
    volumes:
      - /home/tomakahe:/config
      - /srv/dev-disk-by-uuid-540ab9c8-fa76-426e-91a8-7afeddcd5d2d/mastodon-data:/mastodon/public/system
   # extra_hosts:
   #   - "xn--6r9aa.com:192.168.1.16"
   #   - "ꩮꩮ.com:192.168.1.75"

  ## Uncomment to enable federation with tor instances along with adding the following ENV variables
  ## http_hidden_proxy=http://privoxy:8118
  ## ALLOW_ACCESS_TO_HIDDEN_SERVICE=true
  # tor:
  #   image: sirboops/tor
  #   networks:
  #      - external_network
  #      - internal_network
  #
  # privoxy:
  #   image: sirboops/privoxy
  #   volumes:
  #     - ./priv-config:/opt/config
  #   networks:
  #     - external_network
  #     - internal_network

networks:
  mastodon_network:
    driver: bridge
  reverse_proxy:
    driver: bridge

volumes:
  postgres_mastodon:
